
/* eslint-disable prettier/prettier */
// This file is auto-generated. Do not edit manually.
import { NavMenuResponse } from '@/types/menus';

export const headermenu: NavMenuResponse = {
  "term_id": 82,
  "name": "header-nav",
  "slug": "header-nav",
  "term_group": 0,
  "term_taxonomy_id": 82,
  "taxonomy": "nav_menu",
  "description": "",
  "parent": 0,
  "count": 15,
  "filter": "raw",
  "items": [
    {
      "ID": 4984,
      "post_author": "2",
      "post_date": "2025-10-05 15:32:06",
      "post_date_gmt": "2025-05-20 20:41:33",
      "post_content": "",
      "post_title": "Produkty",
      "post_excerpt": "",
      "post_status": "publish",
      "comment_status": "closed",
      "ping_status": "closed",
      "post_password": "",
      "post_name": "produkty",
      "to_ping": "",
      "pinged": "",
      "post_modified": "2025-10-05 15:32:06",
      "post_modified_gmt": "2025-10-05 15:32:06",
      "post_content_filtered": "",
      "post_parent": 0,
      "guid": "https://fortguns.pl/?p=4984",
      "menu_order": 1,
      "post_type": "nav_menu_item",
      "post_mime_type": "",
      "comment_count": "0",
      "filter": "raw",
      "db_id": 4984,
      "menu_item_parent": "0",
      "object_id": "4984",
      "object": "custom",
      "type": "custom",
      "type_label": "Własny odnośnik",
      "title": "Produkty",
      "url": "/produkty",
      "target": "",
      "attr_title": "",
      "description": "",
      "classes": [
        ""
      ],
      "xfn": "",
      "child_items": [
        {
          "ID": 4987,
          "post_author": "2",
          "post_date": "2025-10-05 15:32:06",
          "post_date_gmt": "2025-05-20 20:47:59",
          "post_content": "",
          "post_title": "Broń nowa",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bron-nowa",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2025-10-05 15:32:06",
          "post_modified_gmt": "2025-10-05 15:32:06",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://fortguns.pl/?p=4987",
          "menu_order": 2,
          "post_type": "nav_menu_item",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "db_id": 4987,
          "menu_item_parent": "4984",
          "object_id": "4987",
          "object": "custom",
          "type": "custom",
          "type_label": "Własny odnośnik",
          "title": "Broń nowa",
          "url": "/produkty/kategoria/bron-nowa",
          "target": "",
          "attr_title": "",
          "description": "",
          "classes": [
            ""
          ],
          "xfn": "",
          "child_items": [
            {
              "ID": 4988,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Pistolety",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "pistolety",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4988",
              "menu_order": 3,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4988,
              "menu_item_parent": "4987",
              "object_id": "4988",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Pistolety",
              "url": "/produkty/kategoria/pistolety",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            },
            {
              "ID": 4989,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Karabiny",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "karabiny",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4989",
              "menu_order": 4,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4989,
              "menu_item_parent": "4987",
              "object_id": "4989",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Karabiny",
              "url": "/produkty/kategoria/karabiny",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            },
            {
              "ID": 4990,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Strzelby",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "strzelby",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4990",
              "menu_order": 5,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4990,
              "menu_item_parent": "4987",
              "object_id": "4990",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Strzelby",
              "url": "/produkty/kategoria/strzelby",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            },
            {
              "ID": 4991,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Rewolwery",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "rewolwery",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4991",
              "menu_order": 6,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4991,
              "menu_item_parent": "4987",
              "object_id": "4991",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Rewolwery",
              "url": "/produkty/kategoria/rewolwery",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            }
          ]
        },
        {
          "ID": 4986,
          "post_author": "2",
          "post_date": "2025-10-05 15:32:06",
          "post_date_gmt": "2025-05-20 20:47:59",
          "post_content": "",
          "post_title": "Broń używana",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "bron-uzywana-2",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2025-10-05 15:32:06",
          "post_modified_gmt": "2025-10-05 15:32:06",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://fortguns.pl/?p=4986",
          "menu_order": 7,
          "post_type": "nav_menu_item",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "db_id": 4986,
          "menu_item_parent": "4984",
          "object_id": "4986",
          "object": "custom",
          "type": "custom",
          "type_label": "Własny odnośnik",
          "title": "Broń używana",
          "url": "/produkty/kategoria/bron-uzywana",
          "target": "",
          "attr_title": "",
          "description": "",
          "classes": [
            ""
          ],
          "xfn": "",
          "child_items": [
            {
              "ID": 4992,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Pistolety",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "pistolety-2",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4992",
              "menu_order": 8,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4992,
              "menu_item_parent": "4986",
              "object_id": "4992",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Pistolety",
              "url": "/produkty/kategoria/pistolety-uzywane",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            },
            {
              "ID": 4993,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Karabiny",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "karabiny-2",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4993",
              "menu_order": 9,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4993,
              "menu_item_parent": "4986",
              "object_id": "4993",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Karabiny",
              "url": "/produkty/kategoria/karabiny-uzywana",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            },
            {
              "ID": 4994,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Strzelby",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "strzelby-2",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4994",
              "menu_order": 10,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4994,
              "menu_item_parent": "4986",
              "object_id": "4994",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Strzelby",
              "url": "/produkty/kategoria/strzelby-uzywane",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            },
            {
              "ID": 4995,
              "post_author": "2",
              "post_date": "2025-10-05 15:32:06",
              "post_date_gmt": "2025-05-20 20:47:59",
              "post_content": "",
              "post_title": "Rewolwery",
              "post_excerpt": "",
              "post_status": "publish",
              "comment_status": "closed",
              "ping_status": "closed",
              "post_password": "",
              "post_name": "rewolwery-2",
              "to_ping": "",
              "pinged": "",
              "post_modified": "2025-10-05 15:32:06",
              "post_modified_gmt": "2025-10-05 15:32:06",
              "post_content_filtered": "",
              "post_parent": 0,
              "guid": "https://fortguns.pl/?p=4995",
              "menu_order": 11,
              "post_type": "nav_menu_item",
              "post_mime_type": "",
              "comment_count": "0",
              "filter": "raw",
              "db_id": 4995,
              "menu_item_parent": "4986",
              "object_id": "4995",
              "object": "custom",
              "type": "custom",
              "type_label": "Własny odnośnik",
              "title": "Rewolwery",
              "url": "/produkty/kategoria/rewolwery-uzywane",
              "target": "",
              "attr_title": "",
              "description": "",
              "classes": [
                ""
              ],
              "xfn": ""
            }
          ]
        },
        {
          "ID": 4985,
          "post_author": "2",
          "post_date": "2025-10-05 15:32:06",
          "post_date_gmt": "2025-05-20 20:41:33",
          "post_content": "",
          "post_title": "Amunicja",
          "post_excerpt": "",
          "post_status": "publish",
          "comment_status": "closed",
          "ping_status": "closed",
          "post_password": "",
          "post_name": "amunicja",
          "to_ping": "",
          "pinged": "",
          "post_modified": "2025-10-05 15:32:06",
          "post_modified_gmt": "2025-10-05 15:32:06",
          "post_content_filtered": "",
          "post_parent": 0,
          "guid": "https://fortguns.pl/?p=4985",
          "menu_order": 12,
          "post_type": "nav_menu_item",
          "post_mime_type": "",
          "comment_count": "0",
          "filter": "raw",
          "db_id": 4985,
          "menu_item_parent": "4984",
          "object_id": "4985",
          "object": "custom",
          "type": "custom",
          "type_label": "Własny odnośnik",
          "title": "Amunicja",
          "url": "/produkty/kategoria/amunicja",
          "target": "",
          "attr_title": "",
          "description": "",
          "classes": [
            ""
          ],
          "xfn": ""
        }
      ]
    },
    {
      "ID": 6013,
      "post_author": "2",
      "post_date": "2025-10-05 15:32:06",
      "post_date_gmt": "2025-08-22 16:27:14",
      "post_content": "",
      "post_title": "Marki",
      "post_excerpt": "",
      "post_status": "publish",
      "comment_status": "closed",
      "ping_status": "closed",
      "post_password": "",
      "post_name": "marki",
      "to_ping": "",
      "pinged": "",
      "post_modified": "2025-10-05 15:32:06",
      "post_modified_gmt": "2025-10-05 15:32:06",
      "post_content_filtered": "",
      "post_parent": 0,
      "guid": "https://fortguns.pl/?p=6013",
      "menu_order": 13,
      "post_type": "nav_menu_item",
      "post_mime_type": "",
      "comment_count": "0",
      "filter": "raw",
      "db_id": 6013,
      "menu_item_parent": "0",
      "object_id": "6013",
      "object": "custom",
      "type": "custom",
      "type_label": "Własny odnośnik",
      "title": "Marki",
      "url": "/marki",
      "target": "",
      "attr_title": "",
      "description": "",
      "classes": [
        ""
      ],
      "xfn": ""
    },
    {
      "ID": 4842,
      "post_author": "2",
      "post_date": "2025-10-05 15:32:06",
      "post_date_gmt": "2025-05-18 16:02:13",
      "post_content": " ",
      "post_title": "",
      "post_excerpt": "",
      "post_status": "publish",
      "comment_status": "closed",
      "ping_status": "closed",
      "post_password": "",
      "post_name": "4842",
      "to_ping": "",
      "pinged": "",
      "post_modified": "2025-10-05 15:32:06",
      "post_modified_gmt": "2025-10-05 15:32:06",
      "post_content_filtered": "",
      "post_parent": 0,
      "guid": "https://fortguns.pl/?p=4842",
      "menu_order": 14,
      "post_type": "nav_menu_item",
      "post_mime_type": "",
      "comment_count": "0",
      "filter": "raw",
      "db_id": 4842,
      "menu_item_parent": "0",
      "object_id": "3304",
      "object": "page",
      "type": "post_type",
      "type_label": "Strona",
      "url": "https://fortguns.pl/najczestsze-pytania/",
      "title": "Pytania",
      "target": "",
      "attr_title": "",
      "description": "",
      "classes": [
        ""
      ],
      "xfn": "",
      "slug": "najczestsze-pytania"
    },
    {
      "ID": 4983,
      "post_author": "2",
      "post_date": "2025-10-05 15:32:06",
      "post_date_gmt": "2025-05-20 20:39:51",
      "post_content": "",
      "post_title": "Kontakt",
      "post_excerpt": "",
      "post_status": "publish",
      "comment_status": "closed",
      "ping_status": "closed",
      "post_password": "",
      "post_name": "kontakt",
      "to_ping": "",
      "pinged": "",
      "post_modified": "2025-10-05 15:32:06",
      "post_modified_gmt": "2025-10-05 15:32:06",
      "post_content_filtered": "",
      "post_parent": 0,
      "guid": "https://fortguns.pl/?p=4983",
      "menu_order": 15,
      "post_type": "nav_menu_item",
      "post_mime_type": "",
      "comment_count": "0",
      "filter": "raw",
      "db_id": 4983,
      "menu_item_parent": "0",
      "object_id": "4983",
      "object": "custom",
      "type": "custom",
      "type_label": "Własny odnośnik",
      "title": "Kontakt",
      "url": "/kontakt",
      "target": "",
      "attr_title": "",
      "description": "",
      "classes": [
        ""
      ],
      "xfn": ""
    }
  ]
};

export default headermenu;
